const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGELANGUAGE: 'CHANGELANGUAGE',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAIL',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAIL',

    FETCH_GET_ALL_SUCCESS: 'FETCH_GET_ALL_SUCCESS',
    FETCH_GET_ALL_FAILED: 'FETCH_GET_ALL_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAIL',

    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //Doctor
    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAILED: 'FETCH_TOP_DOCTOR_FAILED',

    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAILED: 'FETCH_ALL_DOCTOR_FAILED',

    SAVE_INFO_DOCTOR_SUCCESS: 'SAVE_INFO_DOCTOR_SUCCESS',
    SAVE_INFO_DOCTOR_FAILED: 'SAVE_INFO_DOCTOR_FAILED',

    GET_DETAIL_DOCTOR_SUCCESS: 'GET_DETAIL_DOCTOR_SUCCESS',
    GET_DETAIL_DOCTOR_FAILED: 'GET_DETAIL_DOCTOR_FAILED',

    GET_MARKDOWN_DOCTOR_SUCCESS: 'GET_MARKDOWN_DOCTOR_SUCCESS',
    GET_MARKDOWN_DOCTOR_FAILED: 'GET_MARKDOWN_DOCTOR_FAILED',

    PUT_MARKDOWN_DOCTOR_SUCCESS: 'PUT_MARKDOWN_DOCTOR_SUCCESS',
    PUT_MARKDOWN_DOCTOR_FAILED: 'PUT_MARKDOWN_DOCTOR_FAILED',

    FETCH_SCHEDULE_TIMES_SUCCESS: 'FETCH_SCHEDULE_TIMES_SUCCESS',
    FETCH_SCHEDULE_TIMES_FAILED: 'FETCH_SCHEDULE_TIMES_FAILED',

    FETCH_REQUITED_DOCTOR_SUCCESS: 'FETCH_REQUITED_DOCTOR_SUCCESS',
    FETCH_REQUITED_DOCTOR_FAILED: 'FETCH_REQUITED_DOCTOR_FAILED',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
});

export default actionTypes;
